[package]
name = "protocol"
version = "0.1.0"
authors = ["Dylan McKay <dylanmckay34@gmail.com>"]

description = "Easy protocol definitions"
license = "MIT"
repository = "https://github.com/dylanmckay/protocol"

[dependencies]
byteorder = "0.5.3"

[dev-dependencies]
stainless = "0.1.7"

