[package]
name = "protocol-derive-tests"
version = "0.3.3"
authors = ["Dylan McKay <me@dylanmckay.io>"]

publish = false

[dependencies]
protocol = { path = "../protocol" }
protocol-derive = { path = "../protocol-derive" }

