[package]
name = "protocol-derive"
version = "0.3.3"
authors = ["Dylan McKay <me@dylanmckay.io>"]

description = "Easy protocol definitions"
license = "MIT"
repository = "https://github.com/dylanmckay/protocol"
documentation = "https://docs.rs/protocol"
keywords = ["protocol", "tcp", "udp", "connection", "encoding"]


[lib]
proc-macro = true

[dependencies]
syn = "0.12.13"
quote = "0.4.2"

